/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Ventana;

import java.awt.Image;
import java.awt.Toolkit;
import javax.swing.JOptionPane;

/**
 *
 * @author ASUS
 */
public class Ventanas extends javax.swing.JFrame {

    /**
     * Creates new form Ventanas
     */
    public Ventanas() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    @Override
    public Image getIconImage(){
        Image retvalue = Toolkit.getDefaultToolkit().getImage(ClassLoader.getSystemResource("Imagenes/625169.png"));
        return retvalue;
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonSalir = new javax.swing.JButton();
        jLogo = new javax.swing.JLabel();
        jpassword = new javax.swing.JLabel();
        jid = new javax.swing.JLabel();
        jpasswordusuario = new javax.swing.JPasswordField();
        jidusuario = new javax.swing.JTextField();
        jButtonLogin = new javax.swing.JButton();
        jwallpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setIconImage(getIconImage());
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonSalir.setBackground(new java.awt.Color(51, 0, 102));
        jButtonSalir.setForeground(new java.awt.Color(255, 255, 255));
        jButtonSalir.setText("Salir");
        jButtonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(700, 0, 60, 20));

        jLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/Logo.png"))); // NOI18N
        getContentPane().add(jLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 140, -1, 60));

        jpassword.setBackground(new java.awt.Color(255, 255, 255));
        jpassword.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        jpassword.setForeground(new java.awt.Color(255, 255, 255));
        jpassword.setText("PASSWORD :");
        getContentPane().add(jpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, 90, 20));

        jid.setBackground(new java.awt.Color(255, 255, 255));
        jid.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 1, 14)); // NOI18N
        jid.setForeground(new java.awt.Color(255, 255, 255));
        jid.setText("             ID :");
        getContentPane().add(jid, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 250, 90, 20));

        jpasswordusuario.setBackground(new java.awt.Color(0, 0, 0));
        jpasswordusuario.setFont(new java.awt.Font("Berlin Sans FB", 3, 14)); // NOI18N
        jpasswordusuario.setForeground(new java.awt.Color(255, 255, 255));
        jpasswordusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jpasswordusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jpasswordusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 290, 180, 20));

        jidusuario.setBackground(new java.awt.Color(0, 0, 0));
        jidusuario.setFont(new java.awt.Font("Tw Cen MT Condensed Extra Bold", 0, 12)); // NOI18N
        jidusuario.setForeground(new java.awt.Color(255, 255, 255));
        jidusuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jidusuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jidusuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 250, 180, 20));

        jButtonLogin.setBackground(new java.awt.Color(51, 0, 153));
        jButtonLogin.setText("Login");
        jButtonLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLoginActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 330, -1, -1));

        jwallpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/sunrise-illustration-digital-art-uhdpaper.com-4K-4.1963-wp.thumbnail.jpg"))); // NOI18N
        getContentPane().add(jwallpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-20, -3, 780, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalirActionPerformed
   
        System.exit(0);    
    }//GEN-LAST:event_jButtonSalirActionPerformed

    private void jpasswordusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jpasswordusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jpasswordusuarioActionPerformed

    private void jButtonLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLoginActionPerformed
        String usuario = jidusuario.getText();
        String password = jpasswordusuario.getText();
        
        if (usuario.isEmpty() || password.isEmpty()) {
            JOptionPane.showMessageDialog(null,"COMPLETE EL ESPACIO VACIO");
            
        }else{
            if (usuario.equals("admin") && password.equals("123")) {             
                Panel_Control pc = new Panel_Control();
                pc.setVisible(true);
                this.dispose();
                
            }
        }
    }//GEN-LAST:event_jButtonLoginActionPerformed

    private void jidusuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jidusuarioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jidusuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventanas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventanas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonLogin;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLogo;
    private javax.swing.JLabel jid;
    private javax.swing.JTextField jidusuario;
    private javax.swing.JLabel jpassword;
    private javax.swing.JPasswordField jpasswordusuario;
    private javax.swing.JLabel jwallpaper;
    // End of variables declaration//GEN-END:variables
}
